// UCSD AKPsi Website Color Variables

export const akpsiColors = {
  navBarBg: 'bg-gray-800/25',
  navBarBorder: 'border-gray-600/20',
  navBarText: 'text-white',
  navBarTextActive: 'text-yellow-100',
  navBarTextHover: 'hover:text-yellow-100',
  navBarBgActive: 'bg-gray-900/20',
  navBarBgHover: 'hover:bg-gray-900/10',
  heroTitle: 'text-white',
  heroSubtitle: 'text-white',
  sectionTitle: 'text-blue-900',
  sectionSubtitle: 'text-blue-800',
  sectionText: 'text-gray-700',
  sectionBg: 'bg-white',
  mainBg: 'bg-gray-50',
  statCircleBg: 'bg-gray-200',
  statCircleText: 'text-gray-500',
  contactButton: 'bg-gray-800 text-white hover:bg-gray-700',
  contactButtonText: 'text-white',
  contactButtonHover: 'hover:bg-gray-700',
  footerText: 'text-white',
  footerIcon: 'text-white hover:text-white/80',
  footerLogin: 'text-white hover:text-white/80',
  black: 'text-black',
  orangeGradient: 'from-gray-50 via-orange-50 to-gray-50',
  errorText: 'text-red-600',
  inputPlaceholder: 'placeholder-gray-500',
  focusRing: 'focus:ring-blue-500',
  focusBorder: 'focus:border-blue-500',
  glassBg: 'bg-white/60',
  glassHover: 'hover:bg-black/40',
  glassText: 'text-black',
  glassHoverText: 'hover:text-white',
  inputGlass: 'bg-white/70',
  inputBorder: 'border-white/50',
  inputFocus: 'focus:bg-white/80',
}; 